### ISSUE TITLE
Breweries that do not have yelp entries

### ISSUE THREAD

**Issue by Aturberv** [Aturberv/NYCBeerMap#27]
Braven Brewing Company: http://www.brewerydb.com/brewery/gOoZYW
Kelso Beer Company: http://www.brewerydb.com/brewery/gj68bh
Grimm Artisanal Ales: http://www.brewerydb.com/brewery/laNl6e
Alphabet City Brewing Company: http://www.brewerydb.com/brewery/wlbqd0 -- yelp business unclaimed, theres also Alphabet City Beer Co, unsure if they're related, the address on brewery db is set to Alphabet City Beer Co, but on yelp it seemed to be just a normal beer.
Magellanic Brewery - http://www.brewerydb.com/brewery/nnn6Sq
77 Beer Co - http://www.brewerydb.com/brewery/R9Ckuq
Bomb Beer Co - http://www.brewerydb.com/brewery/Wjong1
Original Sin - http://www.brewerydb.com/brewery/EnDjqH
Ruckus Brewing Co - http://www.brewerydb.com/brewery/larXrM
Big Alice Brewing Co - http://www.brewerydb.com/brewery/fmeNDi

**Comment by ryansydnor** [comment]
Given the big thing we need from yelp is a rating (and we're planning on pulling other ratings anyway) we could just put a conditional to _not_ make the query if a `yelpBusinessId` doesn't exist.

**Comment by ryansydnor** [comment]
This PR: https://github.com/Aturberv/NYCBeerMap/pull/46

# Added
Kings county brewers collective

# Done
Alphabet City - no yelp
Grimm - no yelp or google. put them in the middle of prospect park (wishful thinking)
Braven Brewing - no google or yelp. put them in the middle of bushwick
original sin hard cider - i doubt they do their brewing in manhattan. seems like its probably the corporate office. adding for now
ruckus - no yelp or google.
big alice brewing

# Not done
Magellanic - no google, yelp, or untappd entry.
Kelso - closed
77 beer co is in Wisconsin and the beer is served at a random bar on the LES
bomb beer co - closed
